### ISSUE TITLE
 Retrieve a product from the catalog

### ISSUE THREAD

**Issue by pentacros** [PENTACROS/agile-final-project#2]
As a customer,
I need to retrieve a product from the catalog,
So that I can view its details before making a purchase.

**Comment by PENTACROS** [comment]
Given I am an e-commerce manager,
When I update a product’s price,
Then the catalog should reflect the updated information.

**Comment by pentacros** [comment]
Given I am a customer,
When I search for a product by its unique ID,
Then I should see the full details of the product, including name, price, description, and stock availability.
